# Generated by Django 3.2.4 on 2021-07-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False, verbose_name='系统标识')),
                ('name', models.CharField(max_length=512, verbose_name='插件名称')),
                ('developer', models.CharField(max_length=512, verbose_name='开发者')),
                ('pluginVersion', models.CharField(max_length=20, verbose_name='版本')),
                ('pluginDescription', models.CharField(max_length=1024, verbose_name='描述')),
                ('useCounting', models.IntegerField(verbose_name='引用')),
                ('likeCounting', models.IntegerField(verbose_name='引用')),
                ('copyright', models.CharField(max_length=512, verbose_name='版权所有')),
                ('keywords', models.CharField(max_length=512, verbose_name='关键词')),
                ('pluginType', models.CharField(max_length=32, verbose_name='插件类型')),
                ('logo', models.CharField(max_length=512, verbose_name='商标')),
                ('defaultOptions', models.CharField(max_length=512, verbose_name='默认参数')),
                ('createDatetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lastupdate', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('license', models.CharField(max_length=512, verbose_name='许可证')),
                ('isFree', models.SmallIntegerField(verbose_name='免费')),
                ('pricing', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('banned', models.SmallIntegerField(verbose_name='是否封禁')),
                ('parent', models.CharField(max_length=22, verbose_name='父节点')),
                ('currOwner', models.CharField(max_length=22, verbose_name='当前所有人')),
                ('owner', models.CharField(max_length=22, verbose_name='组织所有人')),
            ],
            options={
                'db_table': 'Plugin',
            },
        ),
    ]
