# Generated by Django 3.2.4 on 2021-07-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PluginMaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='banned',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='是否封禁'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='copyright',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='版权所有'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='createDatetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='currOwner',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='当前所有人'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='defaultOptions',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='默认参数'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='developer',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='开发者'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='isFree',
            field=models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='免费'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='keywords',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='lastupdate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最后更新'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='license',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='许可证'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='likeCounting',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='引用'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='logo',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='商标'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='插件名称'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='owner',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='组织所有人'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='parent',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='父节点'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='pluginDescription',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='pluginType',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='插件类型'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='pluginVersion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='pricing',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='useCounting',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='引用'),
        ),
    ]
